### ISSUE TITLE
polling_enginein get_least_used_polling_engine\nIndexError: list index out of range

### ISSUE THREAD

**Issue by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#7]
I get this the below "get_least_used_polling_engine\nIndexError: list index out of range error" on lab with standalone solarwinds server. Here  my playbook task:

  - name: Add SNMP node to Solarwinds
    solarwinds.orion.orion_node:
      <<: *solarwinds_info
      state: present
      name: "{{ inventory_hostname }}"
      ip_address: "{{ ansible_host }}"
      polling_method: SNMP
      snmp_version: 3
      snmpv3_auth_key: "{{ snmpv3_auth_pass}}" 
      snmpv3_auth_method: SHA1
      snmpv3_priv_key: "{{ snmpv3_priv_pass}}"
      snmpv3_priv_method: AES128
      snmpv3_username:  "{{ snmpv3_user}}" 
    delegate_to: localhost

     If I add the this option: "polling_engine: 1" it resolved the issue.  Also, I don't have this issue in production with HA deployment of solarinwinds and can leave off the polling_engine option and have no problems.

TASK [Add SNMP node to Solarwinds] *********************************************
task path: /home/andrewba/automation/playbooks/orion_add_node.yml:44
Trying secret FileVaultSecret(filename='/home/andrewba/vault.pass') for vault_id=default
Trying secret FileVaultSecret(filename='/home/andrewba/vault.pass') for vault_id=default
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/runner/.ansible/tmp `"&& mkdir "` echo /home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559 `" && echo ansible-tmp-1692374443.8826163-28-151656626757559="` echo /home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559 `" ) && sleep 0'
Trying secret FileVaultSecret(filename='/home/andrewba/vault.pass') for vault_id=default
Using module file /usr/share/ansible/collections/ansible_collections/solarwinds/orion/plugins/modules/orion_node.py
<localhost> PUT /home/runner/.ansible/tmp/ansible-local-23cznkubuh/tmpvncihqj4 TO /home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/ /home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.8 /home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py && sleep 0'
Trying secret FileVaultSecret(filename='/home/andrewba/vault.pass') for vault_id=default
<localhost> EXEC /bin/sh -c 'rm -f -r /home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py", line 107, in <module>
    _ansiballz_main()
  File "/home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.solarwinds.orion.plugins.modules.orion_node', init_globals=dict(_module_fqn='ansible_collections.solarwinds.orion.plugins.modules.orion_node', _modlib_path=modlib_path),
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_solarwinds.orion.orion_node_payload_d439z16s/ansible_solarwinds.orion.orion_node_payload.zip/ansible_collections/solarwinds/orion/plugins/modules/orion_node.py", line 531, in <module>
  File "/tmp/ansible_solarwinds.orion.orion_node_payload_d439z16s/ansible_solarwinds.orion.orion_node_payload.zip/ansible_collections/solarwinds/orion/plugins/modules/orion_node.py", line 494, in main
  File "/tmp/ansible_solarwinds.orion.orion_node_payload_d439z16s/ansible_solarwinds.orion.orion_node_payload.zip/ansible_collections/solarwinds/orion/plugins/modules/orion_node.py", line 288, in add_node
  File "/tmp/ansible_solarwinds.orion.orion_node_payload_d439z16s/ansible_solarwinds.orion.orion_node_payload.zip/ansible_collections/solarwinds/orion/plugins/module_utils/orion.py", line 296, in get_least_used_polling_engine
IndexError: list index out of range
fatal: [RT-01 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1692374443.8826163-28-151656626757559/AnsiballZ_orion_node.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.solarwinds.orion.plugins.modules.orion_node', init_globals=dict(_module_fqn='ansible_collections.solarwinds.orion.plugins.modules.orion_node', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_solarwinds.orion.orion_node_payload_d439z16s/ansible_solarwinds.orion.orion_node_payload.zip/ansible_collections/solarwinds/orion/plugins/modules/orion_node.py\", line 531, in <module>\n  File \"/tmp/ansible_solarwinds.orion.orion_node_payload_d439z16s/ansible_solarwinds.orion.orion_node_payload.zip/ansible_collections/solarwinds/orion/plugins/modules/orion_node.py\", line 494, in main\n  File \"/tmp/ansible_solarwinds.orion.orion_node_payload_d439z16s/ansible_solarwinds.orion.orion_node_payload.zip/ansible_collections/solarwinds/orion/plugins/modules/orion_node.py\", line 288, in add_node\n  File \"/tmp/ansible_solarwinds.orion.orion_node_payload_d439z16s/ansible_solarwinds.orion.orion_node_payload.zip/ansible_collections/solarwinds/orion/plugins/module_utils/orion.py\", line 296, in get_least_used_polling_engine\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by jeisenbath** [comment]
I don't have an environment with only one poller to test on, can you try some things out and provide the results?

I'd like to know what these queries return:
SELECT count(EngineId) as NumEngines FROM Orion.Engines
SELECT Nodes, EngineID FROM Orion.Engines ORDER BY Nodes asc

I'm probably not doing the logic the best there, but it sounds like the count query is returning something other than 1 (possibly 0?) which puts the index out of range on "queryengines['results'][0]['NumEngines']"

**Comment by Andyjb8** [comment]
It looks like it was returning nothing. which explains why I got the "list index out of range" error. I am not sure if this is the best way to do it, but updated to this and it works with one poller, but I haven't tested it with multiple pollers yet.

```
    def get_least_used_polling_engine(self):
        queryengines = self.swis.query("SELECT count(EngineId) as NumEngines FROM Orion.Engines")
        totalpollingengines = queryengines['results'][0]['NumEngines']
    
        if totalpollingengines != 1:
            queryleast = self.swis.query("SELECT TOP 1 Nodes, EngineID FROM Orion.Engines WHERE EngineID != 1 ORDER BY Nodes asc")
            if queryleast['results']:  # Check if results are not empty
                leastusedpollingengine = queryleast['results'][0]['EngineID']
                return leastusedpollingengine
            else:
                return "1"  # Replace with an appropriate default EngineID if necessary
        else:
            return "1"  # Default value when there's only one engine

```

**Comment by jeisenbath** [comment]
I pushed 1.0.3 to update the logic for get_least_used_polling_engine. Converting the count to an int and using a greater than comparison should handle the 0 count. Let me know if this doesn't work for you, tested OK on my multiple poller env.
